### PR TITLE
Mostly formatting

### PR DESCRIPTION
**Pull request by DJshelfmushroom**
Move styles to seperate file. Move scripts to seprate file. Move inline styles to seperate stylesheet.

### CODE REVIEW

**Comment by DJshelfmushroom** [comment]
huh. it's blinding white now. must've broken something

**Comment by DJshelfmushroom** [comment]
do not merge

**Comment by DJshelfmushroom** [comment]
ready to merge

**Comment by DJshelfmushroom** [comment]
@dragon731012

**Comment by DJshelfmushroom** [comment]
lol thanks

**Comment by dragon731012** [comment]
Np

**Pull request merged**
